"""Re-export models so Alembic autogenerate sees them."""

from app.models.models import (  # noqa: F401
    Activity,
    AgentAction,
    AppSetting,
    AthleteProfile,
    CoachConversation,
    CoachMemory,
    CoachMessage,
    CoachPlanProposal,
    Competition,
    CompetitionMealPlan,
    CompetitionNutritionPlan,
    DailyBrief,
    DataSummary,
    DayTypeOverride,
    GarminMetric,
    MentalEntry,
    NutritionDraft,
    NutritionEstimate,
    NutritionLog,
    NutritionPlan,
    NutritionTargetAssignment,
    Recipe,
    SavedFood,
    TrainingPlan,
    USDAFood,
    VoiceDraft,
    WorkoutDayRevision,
    WorkoutLog,
    WorkoutOverride,
)
