"""Shopping-list aggregation.

`build_shopping_list` aggregates ingredients across N existing day plans
(generated by `app.agents.mealplan.generate_meal_plan`) into a
deduplicated, quantity-totaled list. This is pure code, not LLM.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date, timedelta
from typing import Any

from sqlalchemy import and_, select
from sqlalchemy.orm import Session

from app.models import NutritionPlan


def build_shopping_list(
    db: Session,
    start: date,
    end: date,
) -> dict[str, Any]:
    """Aggregate ingredients across all NutritionPlans in [start, end]."""
    plans = db.scalars(
        select(NutritionPlan)
        .where(and_(NutritionPlan.day >= start, NutritionPlan.day <= end))
        .order_by(NutritionPlan.day)
    ).all()

    totals: dict[str, float] = defaultdict(float)
    days_covered: list[str] = []
    missing_days: list[str] = []
    cur = start
    plan_by_day = {p.day: p for p in plans}
    while cur <= end:
        if cur in plan_by_day:
            days_covered.append(cur.isoformat())
            plan = plan_by_day[cur].plan or {}
            meals = (plan.get("plan") or {}).get("meals") or plan.get("meals") or []
            for meal in meals:
                for ing in meal.get("ingredients") or []:
                    name = (ing.get("name") or "").strip().lower()
                    qty = float(ing.get("qty_g") or 0)
                    if name and qty > 0:
                        totals[name] += qty
        else:
            missing_days.append(cur.isoformat())
        cur += timedelta(days=1)

    items = [
        {"name": k, "qty_g": round(v, 0)} for k, v in sorted(totals.items(), key=lambda kv: -kv[1])
    ]
    return {
        "start": start.isoformat(),
        "end": end.isoformat(),
        "days_covered": days_covered,
        "missing_days": missing_days,
        "items": items,
        "item_count": len(items),
    }
