"""Shopping-list aggregation.

`build_shopping_list` aggregates ingredients across N existing day plans
(generated by `app.agents.mealplan.generate_meal_plan`) into a
deduplicated, quantity-totaled list. This is pure code, not LLM.
"""

from __future__ import annotations

from collections import defaultdict
from datetime import date, timedelta
from math import isfinite
from typing import Any

from sqlalchemy import and_, select
from sqlalchemy.orm import Session

from app.models import NutritionPlan


def plan_meals(payload: Any) -> list[dict[str, Any]]:
    """Read the supported stored day-plan envelopes without treating junk as coverage."""
    current = payload
    for _ in range(3):
        if not isinstance(current, dict):
            return []
        meals = current.get("meals")
        if isinstance(meals, list):
            return [meal for meal in meals if isinstance(meal, dict) and meal.get("name")]
        current = current.get("plan")
    return []


def build_shopping_list(
    db: Session,
    start: date,
    end: date,
) -> dict[str, Any]:
    """Aggregate ingredients across all NutritionPlans in [start, end]."""
    plans = db.scalars(
        select(NutritionPlan)
        .where(and_(NutritionPlan.day >= start, NutritionPlan.day <= end))
        .order_by(NutritionPlan.day)
    ).all()

    totals: dict[str, float] = defaultdict(float)
    days_covered: list[str] = []
    missing_days: list[str] = []
    cur = start
    plan_by_day = {p.day: p for p in plans}
    while cur <= end:
        meals = plan_meals(plan_by_day[cur].plan) if cur in plan_by_day else []
        complete = bool(meals)
        for meal in meals:
            ingredients = meal.get("ingredients")
            if not isinstance(ingredients, list) or not ingredients:
                complete = False
                continue
            for ing in ingredients:
                if not isinstance(ing, dict) or not isinstance(ing.get("name"), str):
                    complete = False
                    continue
                name = ing["name"].strip().lower()
                try:
                    qty = float(ing.get("qty_g") or 0)
                except (TypeError, ValueError):
                    complete = False
                    continue
                if name and isfinite(qty) and qty > 0:
                    totals[name] += qty
                else:
                    complete = False
        if complete:
            days_covered.append(cur.isoformat())
        else:
            missing_days.append(cur.isoformat())
        cur += timedelta(days=1)

    items = [
        {"name": k, "qty_g": round(v, 0)} for k, v in sorted(totals.items(), key=lambda kv: -kv[1])
    ]
    return {
        "start": start.isoformat(),
        "end": end.isoformat(),
        "days_covered": days_covered,
        "missing_days": missing_days,
        "items": items,
        "item_count": len(items),
    }
